
#!/usr/bin/env sh
# Gradle wrapper script generated by Gradle
# This is a minimal wrapper for building the Android app.
# It expects the Gradle wrapper JAR in ./gradle/wrapper/gradle-wrapper.jar.
# If the JAR is missing, it will be downloaded from the default distribution URL.

set -e

# Determine the location of the wrapper JAR
WRAPPER_JAR="$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$WRAPPER_JAR" ]; then
  echo "Wrapper JAR not found, downloading..."
  java -jar "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" --gradle-version 8.5
fi

# Execute Gradle with the wrapper JAR
exec java -jar "$WRAPPER_JAR" "$@"
